[package]
name = "sub_processor"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "substitution_gen_lib_rs"
crate-type = ["cdylib"]

[dependencies]
rayon = "1.8.0"
pyo3="0.19.2"


