class Teacher:
    name: str
    def __new__(name:str,sub:str) -> Teacher: ...

    def add_period(period:int,grade:int,section:str) -> None: ...

    def get_sub() -> str: ...



class Class:
    def __new__(name:str): ...
    def add_teacher(teacher:Teacher,period:int): ...
class School:
    def add_class(c:Class): ...
    # def teacher_by_subjects(subject:str) -> list: ...